
import './globals.css'
import { Inter } from 'next/font/google'



import ThemeProvider from './themeProvider'


export const metadata = {
  title: 'Meme maker',
  description: 'Generated by create next app',
}

 export default function RootLayout({ children }) {
  // const { store, props } = wrapper.useWrappedStore(rest);

  return (
    // <Provider store={store}>
    <html lang="en">
      
      <body >
      <ThemeProvider>
        
        {children}
        </ThemeProvider>
        </body>
    </html>
    // </Provider>

  )
}


// export default store.withRedux(RootLayout)
